[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hiraise = "B4ZgDcF5jok9LMkPzi3LexmhWfxr63rj5dAeas98h2rT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
