import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/themeProvider";
import { ModeToggle } from "@/components/theme/themeToggle";
import { SolanaWalletProvider } from "@/components/wallet/SolanaWalletProvider";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased w-full flex flex-col items-center`}
      >
        <SolanaWalletProvider>
          <div className="w-full max-w-screen-2xl overflow-hidden">
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <div className="w-full flex justify-end py-4 px-8 md:px-12 lg:px-16 xl:px-32">
                <ModeToggle />
              </div>
              {children}
            </ThemeProvider>
          </div>
        </SolanaWalletProvider>
      </body>
    </html>
  );
}
